#!/usr/bin/env python3
"""Emit behavioral 1r1w Verilog stubs for NVDLA SRAM sizes that don't
become bsg_fakeram macros — the very small (<1 KB) ones and the
depth-16 entries that CACTI fails to size on nangate45/sky130hd.

Outputs land at designs/src/NVDLA/dev/generated/sram_ff/fakeram_WxD_1r1w.v.
The pin names mirror bsg_fakeram's 1r1w convention so the same NVDLA
instantiations bind to either a hard macro (via LEF/LIB) or this FF
array depending on which platform/size is in scope.

Run:
    python3 designs/src/NVDLA/dev/gen_ff_rams.py

This is idempotent — re-run whenever the FF size list changes.
"""
import math
import os
import sys

# (width_bits, depth_entries) pairs that should synthesize to FF arrays
# rather than fakeram macros. Names mirror the LEF naming the rest of
# NVDLA expects: fakeram_WxD_1r1w.
FF_SIZES = [
    (6, 128),    #   768 bits — sub-1 KB
    (9, 80),     #   720 bits — sub-1 KB
    (66, 8),     #   528 bits — sub-1 KB
    (64, 16),    #  1024 bits — CACTI fails on n45/sky130hd (D=16 too shallow)
    (256, 16),   #  4096 bits — CACTI fails on n45/sky130hd
    (272, 16),   #  4352 bits — CACTI fails on n45/sky130hd
]


VERILOG_TEMPLATE = """\
// Auto-generated by designs/src/NVDLA/dev/gen_ff_rams.py.
// Behavioral 1r1w SRAM model — synthesizes to a register array (flip-flops)
// because no LEF/LIB is provided for this size. Pin names follow bsg_fakeram's
// 1r1w convention so this stub is a drop-in for the fakeram_WxD_1r1w macros
// produced for the same NVDLA SRAM set.

module {name}
(
   w0_wd_in,
   w0_we_in,
   w0_clk,
   w0_ce_in,
   w0_addr_in,

   r0_rd_out,
   r0_clk,
   r0_ce_in,
   r0_addr_in
);
   parameter BITS = {bits};
   parameter WORD_DEPTH = {depth};
   parameter ADDR_WIDTH = {addr_width};

   input  [BITS-1:0]        w0_wd_in;
   input                    w0_we_in;
   input                    w0_clk;
   input                    w0_ce_in;
   input  [ADDR_WIDTH-1:0]  w0_addr_in;

   output reg [BITS-1:0]    r0_rd_out;
   input                    r0_clk;
   input                    r0_ce_in;
   input  [ADDR_WIDTH-1:0]  r0_addr_in;

   reg [BITS-1:0] mem [0:WORD_DEPTH-1];

   always @(posedge w0_clk) begin
      if (w0_ce_in && w0_we_in)
         mem[w0_addr_in] <= w0_wd_in;
   end

   always @(posedge r0_clk) begin
      if (r0_ce_in)
         r0_rd_out <= mem[r0_addr_in];
   end

endmodule
"""


def emit(width, depth, out_dir):
    name = f"fakeram_{width}x{depth}_1r1w"
    addr_width = max(1, math.ceil(math.log2(depth)))
    body = VERILOG_TEMPLATE.format(
        name=name, bits=width, depth=depth, addr_width=addr_width
    )
    path = os.path.join(out_dir, f"{name}.v")
    with open(path, "w") as fid:
        fid.write(body)
    return path


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    out_dir = os.path.join(here, "generated", "sram_ff")
    os.makedirs(out_dir, exist_ok=True)
    # Wipe stale outputs so an updated FF_SIZES list doesn't leave orphans.
    for f in os.listdir(out_dir):
        if f.endswith(".v"):
            os.remove(os.path.join(out_dir, f))
    for w, d in FF_SIZES:
        path = emit(w, d, out_dir)
        print(f"wrote {os.path.relpath(path, here)}  ({w}x{d}, {w*d} bits)")


if __name__ == "__main__":
    main()
